name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12
  - asttokens=2.0.5
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bleach=4.1.0
  - brotlipy=0.7.0
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cffi=1.14.6
  - chardet=4.0.0
  - colorama=0.4.4
  - cryptography=3.4.7
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.3
  - executing=0.8.3
  - idna=2.10
  - imagesize=1.2.0
  - importlib-metadata=4.8.1
  - ipykernel=6.9.2
  - ipython=8.1.1
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jsonschema=3.2.0
  - jupyter_client=7.0.3
  - jupyter_core=4.8.1
  - jupyterlab_pygments=0.1.2
  - libsodium=1.0.18
  - markdown-it-py=1.1.0
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.3
  - mdit-py-plugins=0.2.8
  - mistune=0.8.4
  - myst-parser=0.15.2
  - nbclient=0.5.4
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - nbsphinx=0.8.1
  - nest-asyncio=1.5.1
  - openmp=13.0.1
  - openssl=1.1.1l
  - packaging=21.0
  - pandoc=2.14.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=22.0.4
  - prompt-toolkit=3.0.27
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.20
  - pygments=2.10.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pypy3.9==7.3.8
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.1
  - pyyaml=5.4.1
  - pyzmq=22.3.0
  - requests=2.25.1
  - setuptools=58.0.4
  - six=1.16.0
  - snowballstemmer=2.1.0
  - sphinx=3.4.3
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlite=3.36.0
  - stack_data=0.2.0
  - testpath=0.5.0
  - tornado=6.1
  - traitlets=5.1.0
  - typing_extensions=3.10.0.0
  - tzdata=2021a
  - urllib3=1.26.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.0
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.5.0
  - pip:
    - docutils==0.18
    - groundwork-sphinx-theme==1.1.1
    - jinja2==2.11.0
    - nbsphinx-link==1.3.0
    - sphinx-rtd-theme==0.5.1
