name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - sphinx==3.4.3
  - nbsphinx==0.8.1
  - nbsphinx-link==1.3.0
  - Jinja2==2.11
  - myst-parser==0.15.2
  - docutils==0.18
  - ipykernel
  - pip
  - pip:
    - sphinx_rtd_theme==0.5.1
    - groundwork-sphinx-theme