name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - numpy
  - sphinx
  - Jinja2<3.1
  - myst-parser
  - nbsphinx
  - nbsphinx-link
  - docutils
  - sphinx-automodapi
  - sphinx-panels
  - sphinx-tabs
  - pip
  - pip:
    - sphinx_rtd_theme
    - groundwork-sphinx-theme